# fly.toml app configuration file generated for kevytlasku-api on 2026-08-20T16:02:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kevytlasku-api'
primary_region = 'arn'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = 'kevytlasku_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
